// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHNtfkGzE0ht4ZGFk4K8gs7E7p9Y33lBc',
    appId: '1:958885347047:web:b1ddc604eef52c0f3dac42',
    messagingSenderId: '958885347047',
    projectId: 'kulosehat',
    authDomain: 'kulosehat.firebaseapp.com',
    storageBucket: 'kulosehat.firebasestorage.app',
    measurementId: 'G-G1FLRM72JF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyUGd9nnlg0aYGRrCzZCdgimkTaiW-30',
    appId: '1:958885347047:ios:5a4fd3aacebfc3913dac42',
    messagingSenderId: '958885347047',
    projectId: 'kulosehat',
    storageBucket: 'kulosehat.firebasestorage.app',
    iosBundleId: 'com.example.kulosehat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyUGd9nnlg0aYGRrCzZCdgimkTaiW-30',
    appId: '1:958885347047:ios:5a4fd3aacebfc3913dac42',
    messagingSenderId: '958885347047',
    projectId: 'kulosehat',
    storageBucket: 'kulosehat.firebasestorage.app',
    iosBundleId: 'com.example.kulosehat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHNtfkGzE0ht4ZGFk4K8gs7E7p9Y33lBc',
    appId: '1:958885347047:web:cecfe413df6150413dac42',
    messagingSenderId: '958885347047',
    projectId: 'kulosehat',
    authDomain: 'kulosehat.firebaseapp.com',
    storageBucket: 'kulosehat.firebasestorage.app',
    measurementId: 'G-21JPZH8VLV',
  );
}
